# Generated by Django 4.2.3 on 2023-07-15 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_rename_count_shortener_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
